<?php
/* GENERATED by _build/wp_build.py from _build/partials/footer.html. Edit the static source and re-run; do not edit this file. */
defined( 'ABSPATH' ) || exit;
?>
  <!-- ================= FOOTER (mirrors the header navigation) ================= -->
  <footer class="footer">
    <div class="wrap">
      <div class="footer__head">
        <a class="brand brand--footer" href="<?php wra_u( '/' ); ?>">
          <img class="brand__logo" src="<?php echo WRA_A; ?>img/brand/wra-logo-nav-72.webp" srcset="<?php echo WRA_A; ?>img/brand/wra-logo-nav-72.webp 1x, <?php echo WRA_A; ?>img/brand/wra-logo-nav-144.webp 2x, <?php echo WRA_A; ?>img/brand/wra-logo-nav-216.webp 3x" width="75" height="72" loading="lazy" alt="Wisconsin Repeater Alliance: Coordinating Wisconsin Amateur Radio">
        </a>
        <p class="footer__statement">A Wisconsin nonprofit corporation and federally recognized <span class="nowrap">501(c)(3)</span> public charity.</p>
      </div>

      <nav class="footer__nav" aria-label="Footer">
        <div>
          <h2><a href="<?php wra_u( '/about/' ); ?>">About WRA</a></h2>
          <ul role="list">
            <li><a href="<?php wra_u( '/about/#who' ); ?>">Who we are</a></li>
            <li><a href="<?php wra_u( '/about/#governance' ); ?>">Governance</a></li>
          </ul>
        </div>
        <div>
          <h2><a href="<?php wra_u( '/frequency-coordination/' ); ?>">Coordination</a></h2>
          <ul role="list">
            <li><a href="<?php wra_u( '/frequency-coordination/' ); ?>">What is frequency coordination?</a></li>
            <li><a href="<?php wra_u( '/repeater-coordination/' ); ?>">Repeater coordination</a></li>
            <li><a href="<?php wra_u( '/repeater-coordination/#checklist' ); ?>">Pre-application checklist</a></li>
          </ul>
        </div>
        <div>
          <h2><a href="<?php wra_u( '/arcs/' ); ?>">ARCS</a></h2>
          <ul role="list">
            <li><a href="<?php wra_u( '/arcs/' ); ?>">About ARCS</a></li>
            <li><a href="https://arcsonline.org/" target="_blank" rel="noopener">Sign in to ARCS<svg aria-hidden="true"><use href="#i-ext"/></svg><span class="visually-hidden"> (opens in a new tab)</span></a></li>
            <li><a href="https://arcsonline.org/repeaters/" target="_blank" rel="noopener">Repeater directory<svg aria-hidden="true"><use href="#i-ext"/></svg><span class="visually-hidden"> (opens in a new tab)</span></a></li>
          </ul>
        </div>
        <div>
          <h2><a href="<?php wra_u( '/membership/' ); ?>">Membership</a></h2>
          <ul role="list">
            <li><a href="<?php wra_u( '/membership/' ); ?>">Join or renew</a></li>
            <li><a href="<?php wra_u( '/membership/#dues' ); ?>">Paying your dues</a></li>
          </ul>
        </div>
        <div>
          <h2><a href="<?php wra_u( '/resources/' ); ?>">Resources</a></h2>
          <ul role="list">
            <li><a href="<?php wra_u( '/resources/#faq' ); ?>">FAQ</a></li>
            <li><a href="<?php wra_u( '/resources/#library' ); ?>">Documents and forms</a></li>
            <li><a href="<?php wra_u( '/resources/#volunteer' ); ?>">Volunteer</a></li>
          </ul>
        </div>
        <div>
          <h2>News and contact</h2>
          <ul role="list">
            <li><a href="<?php wra_u( '/news/' ); ?>">News</a></li>
            <li><a href="<?php wra_u( '/contact/' ); ?>">Contact</a></li>
            <li><a href="<?php wra_u( '/contact/?topic=coordination' ); ?>">Coordination questions</a></li>
            <li><a href="mailto:info@wi-ra.org">Info@wi-ra.org</a></li>
          </ul>
        </div>
      </nav>

      <div class="footer__legal">
        <dl class="footer__facts">
          <div><dt>EIN</dt><dd>42-4481796</dd></div>
          <div><dt>Status</dt><dd><span class="nowrap">501(c)(3)</span> public charity, Section <span class="nowrap">509(a)(2)</span></dd></div>
          <div><dt>Mailing address</dt><dd>1148 N. Sunnyslope Dr, Mount Pleasant, WI 53406</dd></div>
        </dl>
      </div>

      <div class="footer__bottom">
        <p>&copy; 2026 Wisconsin Repeater Alliance, Inc. All rights reserved.</p>
        <ul role="list">
          <li><a href="<?php wra_u( '/resources/#library' ); ?>">Bylaws and policies</a></li>
          <li><a href="<?php wra_u( '/privacy-policy/' ); ?>">Privacy Policy</a></li>
          <li><a href="<?php wra_u( '/terms-of-use/' ); ?>">Terms of Use</a></li>
        </ul>
      </div>
    </div>
  </footer>
