"""Generate the WordPress child theme templates from the static site sources.

The static build (_build/pages + _build/partials, assembled by build.py) is the
approved design and stays the single source of truth. This script turns it into
the WordPress theme in wordpress/theme/wra-child:

  generated (never edit by hand; edit the static source and re-run):
    front-page.php, page-<slug>.php, 404.php
    template-parts/chrome-header.php, template-parts/chrome-footer.php
    template-parts/map.php
    inc/page-meta.php
    assets/css/wra.css, assets/js/wra.js, assets/img/**, assets/icons/**

  hand-written (live in the theme folder): functions.php, header.php,
  footer.php, single.php, page.php, index.php, inc/*.php (except page-meta),
  template-parts/news-*.php, template-parts/arcs-status.php, assets/css/wp.css

Run from anywhere:  python _build/wp_build.py
"""
import json
import pathlib
import re
import shutil

ROOT = pathlib.Path(__file__).resolve().parent.parent
BUILD = ROOT / "_build"
THEME = ROOT / "wordpress" / "theme" / "wra-child"

GEN = "<?php\n/* GENERATED by _build/wp_build.py from {src}. Edit the static source and re-run; do not edit this file. */\ndefined( 'ABSPATH' ) || exit;\n"

# static file -> (template key, WordPress path)
PAGES = {
    "index.html": ("home", "/"),
    "about.html": ("about", "/about/"),
    "coordination.html": ("frequency-coordination", "/frequency-coordination/"),
    "coordination-process.html": ("repeater-coordination", "/repeater-coordination/"),
    "arcs.html": ("arcs", "/arcs/"),
    "membership.html": ("membership", "/membership/"),
    "resources.html": ("resources", "/resources/"),
    "news.html": ("news", "/news/"),
    "contact.html": ("contact", "/contact/"),
    "privacy.html": ("privacy-policy", "/privacy-policy/"),
    "terms.html": ("terms-of-use", "/terms-of-use/"),
    "404.html": ("404", None),
}
# news posts keep their live WordPress URLs (root-level post names)
POSTS = {
    "news-501c3-public-charity-status.html": "/wisconsin-repeater-alliance-receives-federal-501c3-public-charity-status/",
    "news-arcs-development-update.html": "/arcs-amateur-radio-coordination-system/",
    "news-open-letter.html": "/an-open-letter-to-the-wisconsin-amateur-radio-community/",
    "news-war-transition.html": "/wisconsin-association-of-repeaters-transition/",
    "news-welcome.html": "/news-welcome-to-wra/",
}
LINKS = {f: p for f, (k, p) in PAGES.items() if p} | POSTS

URL_ATTRS = r'(?:src|srcset|data-src|data-srcset|href|poster)'


def php_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def wp_path(href):
    """'contact.html?topic=x#y' -> '/contact/?topic=x#y' (None if not an internal page link)."""
    m = re.fullmatch(r"([a-z0-9-]+\.html)([?#].*)?", href)
    if not m or m.group(1) not in LINKS:
        return None
    return LINKS[m.group(1)] + (m.group(2) or "")


def convert_attrs(html, aria_current=False):
    """Rewrite asset paths and internal links inside URL attributes."""
    def fix_value(attr, val):
        if attr == "href":
            p = wp_path(val)
            if p is not None:
                return f"<?php wra_u( {php_str(p)} ); ?>"
        # asset paths, including every candidate in a srcset
        return re.sub(r"(^|(?<=[\s,]))assets/", "<?php echo WRA_A; ?>", val)

    def repl(m):
        attr, val = m.group(1), m.group(2)
        return f'{attr}="{fix_value(attr, val)}"'
    out = re.sub(rf'({URL_ATTRS})="([^"]*)"', repl, html)

    if aria_current:
        # mark exact links to the current page (never on buttons), as build.py does
        def mark(m):
            tag = m.group(0)
            if 'class="btn' in tag:
                return tag
            hm = re.search(r"wra_u\( '([^'#?]+)' \)", tag)
            if not hm:
                return tag
            return tag[:-1] + f"<?php wra_aria_current( {php_str(hm.group(1))} ); ?>>"
        out = re.sub(r"<a [^>]*href=\"<\?php wra_u\( '[^'#?]+' \); \?>\"[^>]*>", mark, out)
    return out


def front_matter(path):
    raw = path.read_text(encoding="utf8")
    m = re.match(r"\s*<!--(.*?)-->\s*", raw, re.S)
    return json.loads(m.group(1)), raw[m.end():]


def balanced_div(html, start):
    """Index just past the </div> that closes the <div ...> opening at `start`."""
    depth, i = 0, start
    for tag in re.finditer(r"<(/?)div\b[^>]*>", html[start:]):
        depth += -1 if tag.group(1) else 1
        if depth == 0:
            return start + tag.end()
    raise ValueError("unbalanced div")


def replace_block(html, start_marker, end_index_fn, replacement):
    a = html.index(start_marker)
    b = end_index_fn(html, a)
    return html[:a] + replacement + html[b:]


def page_specific(key, body):
    if key == "home":
        # the three latest posts come from WordPress
        a = body.index("        <!-- CMS: three most recent posts -->")
        d = body.index('<div class="posts posts--home">', a)
        b = balanced_div(body, d)
        body = body[:a] + "        <?php get_template_part( 'template-parts/news', 'home' ); ?>" + body[b:]
    elif key == "news":
        a = body.index("        <!-- CMS: newest post as the feature")
        b = body.index("</ul>", a) + len("</ul>")
        body = body[:a] + "        <?php get_template_part( 'template-parts/news', 'list' ); ?>" + body[b:]
    elif key == "arcs":
        a = body.index("          <!-- EDITABLE NOTICE")
        d = body.index('<div class="notice"', a)
        b = balanced_div(body, d)
        body = body[:a] + "          <?php get_template_part( 'template-parts/arcs-status' ); ?>" + body[b:]
    elif key in ("contact", "resources"):
        form_id = "contact" if key == "contact" else "volunteer"
        body = re.sub(r"[ \t]*<!-- FORM: [^>]*-->\n", "", body)
        # hidden fields first, while the <form> tag is still plain HTML (the endpoint attribute contains "?>")
        body = re.sub(r'(<form class="form" data-form [^>]*>)',
                      lambda m: m.group(1) + f"\n            <?php wra_form_fields( {php_str(form_id)} ); ?>", body, count=1)
        body = body.replace('<form class="form" data-form ',
                            '<form class="form" data-form data-endpoint="<?php echo esc_url( rest_url( \'wra/v1/message\' ) ); ?>" ', 1)
        if key == "resources":
            # several checkboxes share one name: post them as an array
            body = body.replace('name="areas"', 'name="areas[]"')
    return body


def crumbs_php(crumbs):
    items = []
    for label, href in crumbs:
        path = wp_path(href) if href else None
        items.append(f"array( {php_str(label)}, {php_str(path) if path else 'null'} )")
    return "array( " + ", ".join(items) + " )"


def asset_rel(p):
    return p[len("assets/"):] if p and p.startswith("assets/") else p


def build():
    counts = json.loads((BUILD / "map-counts.json").read_text())
    meta_rows = []

    for fname, (key, path) in PAGES.items():
        meta, body = front_matter(BUILD / "pages" / fname)
        body = body.rstrip() + "\n"
        body = page_specific(key, body)
        body = body.replace("{{crumbs}}", "<?php wra_crumbs(); ?>")
        body = body.replace("@@MAP@@", "<?php get_template_part( 'template-parts/map' ); ?>")
        body = body.replace("@@V@@", str(counts["v"])).replace("@@U@@", str(counts["u"])).replace("@@X@@", str(counts["x"]))
        body = convert_attrs(body)
        assert "{{" not in body and "@@" not in body and ".html\"" not in body, (fname, re.findall(r'href="[^"]*\.html[^"]*"', body)[:3])

        tpl = "front-page.php" if key == "home" else "404.php" if key == "404" else f"page-{key}.php"
        out = GEN.format(src=f"_build/pages/{fname}") + f"wra_page( {php_str(key)} );\nget_header();\n?>\n" + body + "<?php\nget_footer();\n"
        (THEME / tpl).write_text(out, encoding="utf8")
        print(f"  {tpl:40s} <- {fname}")

        pre = meta.get("preload")
        row = {
            "title": meta["title"],
            "description": meta["description"],
            "og_title": meta.get("og_title", meta["title"]),
            "nav": meta.get("nav", ""),
            "path": path or "",
            "noindex": bool(meta.get("noindex")),
        }
        meta_rows.append((key, row, meta.get("crumbs", []), pre))

    # page meta as a PHP array
    lines = [GEN.format(src="_build/pages/*.html front matter").rstrip("\n"), "return array("]
    for key, row, crumbs, pre in meta_rows:
        lines.append(f"\t{php_str(key)} => array(")
        for k, v in row.items():
            lines.append(f"\t\t{php_str(k)} => {('true' if v else 'false') if isinstance(v, bool) else php_str(v)},")
        lines.append(f"\t\t'crumbs' => {crumbs_php(crumbs)},")
        if pre:
            srcset = pre.get("srcset", "")
            srcset = re.sub(r"(^|(?<=[\s,]))assets/", "", srcset)
            lines.append(f"\t\t'preload' => array( 'href' => {php_str(asset_rel(pre['href']))}, 'srcset' => {php_str(srcset)}, 'sizes' => {php_str(pre.get('sizes', '100vw') if srcset else '')} ),")
        lines.append("\t),")
    lines.append(");")
    (THEME / "inc" / "page-meta.php").write_text("\n".join(lines) + "\n", encoding="utf8")
    print("  inc/page-meta.php")

    # shared chrome
    header = (BUILD / "partials" / "header.html").read_text(encoding="utf8")
    header = header[header.index("<body>") + len("<body>"):].lstrip("\n")
    header = re.sub(r'data-nav="([a-z]+)"', lambda m: f'data-nav="{m.group(1)}"<?php wra_nav_current( {php_str(m.group(1))} ); ?>', header)
    header = convert_attrs(header, aria_current=True)
    (THEME / "template-parts" / "chrome-header.php").write_text(GEN.format(src="_build/partials/header.html") + "?>\n" + header, encoding="utf8")

    footer = (BUILD / "partials" / "footer.html").read_text(encoding="utf8")
    footer = footer[: footer.index("</body>")].rstrip() + "\n"
    footer = convert_attrs(footer)
    (THEME / "template-parts" / "chrome-footer.php").write_text(GEN.format(src="_build/partials/footer.html") + "?>\n" + footer, encoding="utf8")

    (THEME / "template-parts" / "map.php").write_text(
        GEN.format(src="_build/map.svg.html") + "?>\n" + (BUILD / "map.svg.html").read_text(encoding="utf8"), encoding="utf8")
    print("  template-parts/chrome-header.php, chrome-footer.php, map.php")

    # assets, unchanged
    (THEME / "assets" / "css").mkdir(parents=True, exist_ok=True)
    (THEME / "assets" / "js").mkdir(parents=True, exist_ok=True)
    shutil.copy2(ROOT / "css" / "wra.css", THEME / "assets" / "css" / "wra.css")
    shutil.copy2(ROOT / "js" / "wra.js", THEME / "assets" / "js" / "wra.js")
    for sub in ("img", "icons", "docs"):
        dst = THEME / "assets" / sub
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(ROOT / "assets" / sub, dst, ignore=shutil.ignore_patterns("CREDITS.txt"))
    shutil.copy2(ROOT / "assets" / "img" / "photos" / "CREDITS.txt", THEME / "assets" / "img" / "photos" / "CREDITS.txt")
    print("  assets copied")

    # the generated templates may only reference helpers the theme defines
    used = set()
    for f in THEME.rglob("*.php"):
        used |= set(re.findall(r"\b(wra_[a-z_]+)\s*\(", f.read_text(encoding="utf8")))
    defined = set()
    for f in (THEME / "inc").glob("*.php"):
        defined |= set(re.findall(r"function\s+(wra_[a-z_]+)\s*\(", f.read_text(encoding="utf8")))
    plugin_api = {"wra_site_arcs_status", "wra_site_byline"}  # provided by the wra-site plugin, always guarded with function_exists
    missing = used - defined - plugin_api
    assert not missing, f"templates call undefined helpers: {sorted(missing)}"


def export_posts():
    """The approved news posts, for the one-time setup step (wra-setup plugin)."""
    listing = (BUILD / "pages" / "news.html").read_text(encoding="utf8")
    home = (BUILD / "pages" / "index.html").read_text(encoding="utf8")
    # newest first, as the News page lists them; posts sharing a date keep that order through their times
    order = [m for m in re.findall(r'href="(news-[a-z0-9-]+\.html)"', listing) if m in POSTS]
    order = list(dict.fromkeys(order))
    posts = []
    for fname, path in POSTS.items():
        meta, body = front_matter(BUILD / "pages" / fname)
        art = re.search(r'<article class="article__body prose"[^>]*>\s*(.*?)\s*</article>', body, re.S).group(1)
        art = "\n".join(line.strip() for line in art.splitlines() if line.strip())
        # internal links become root-relative WordPress URLs
        art = re.sub(r'href="([^"]+\.html[^"]*)"', lambda m: f'href="{wp_path(m.group(1)) or m.group(1)}"', art)
        assert ".html" not in art and "assets/" not in art, fname
        plate = re.search(r'aside-plate"><img src="assets/([^"]+)"[^>]*alt="([^"]*)"', body)
        byline = re.search(r'<p class="byline"><b>(.*?)</b>', body).group(1)
        # card summary: the home-page card if the post is there, else the archive row / feature
        summary = None
        for src in (home, listing):
            m = re.search(r'<a href="' + re.escape(fname) + r'">.*?</a></h3>\s*<p>(.*?)</p>', src, re.S)
            if m:
                summary = m.group(1)
                break
        posts.append({
            "slug": path.strip("/"),
            "title": re.sub(r"<[^>]+>", "", meta["h1"]),
            "date": meta["article"]["date"],
            "datetime": meta["article"]["date"] + " 12:%02d:00" % (59 - order.index(fname)),
            "byline": "" if byline == "Wisconsin Repeater Alliance" else byline,
            "excerpt": re.sub(r"<[^>]+>", "", summary or ""),
            "image": plate.group(1).replace("-480.", "-900.").replace("-320.", "-640."),
            "image_alt": plate.group(2),
            "content": art,
        })
    out = ROOT / "wordpress" / "plugins" / "wra-setup" / "content"
    out.mkdir(parents=True, exist_ok=True)
    (out / "posts.json").write_text(json.dumps(posts, indent=1, ensure_ascii=False), encoding="utf8")
    print(f"  plugins/wra-setup/content/posts.json ({len(posts)} posts)")


if __name__ == "__main__":
    for d in ("inc", "template-parts"):
        (THEME / d).mkdir(parents=True, exist_ok=True)
    build()
    export_posts()
