<?php
/* GENERATED by _build/wp_build.py from _build/pages/404.html. Edit the static source and re-run; do not edit this file. */
defined( 'ABSPATH' ) || exit;
wra_page( '404' );
get_header();
?>
<main id="main">
    <section class="phead phead--plain" aria-labelledby="page-title">
      <div class="phead__rings" aria-hidden="true"><i></i><i></i><i></i></div>
      <div class="wrap phead__inner">
        <?php wra_crumbs(); ?>
        <h1 class="phead__title" id="page-title">Page not found</h1>
        <p class="phead__lead">The page may have moved when the site was rebuilt. These are the most-used destinations.</p>
      </div>
    </section>

    <section class="sec sec--first">
      <div class="wrap grid split">
        <div class="split__head">
          <h2 class="eyebrow">Error 404</h2>
          <p class="statement statement--sm">Try one of these instead</p>
        </div>
        <div class="split__body">
          <div class="cells cells--2">
            <a class="cell" href="<?php wra_u( '/' ); ?>"><span class="cell__idx">01</span><span class="cell__title">Home</span></a>
            <a class="cell" href="<?php wra_u( '/repeater-coordination/' ); ?>"><span class="cell__idx">02</span><span class="cell__title">Repeater coordination</span></a>
            <a class="cell" href="<?php wra_u( '/membership/' ); ?>"><span class="cell__idx">03</span><span class="cell__title">Join or renew</span></a>
            <a class="cell" href="<?php wra_u( '/resources/#faq' ); ?>"><span class="cell__idx">04</span><span class="cell__title">FAQ</span></a>
            <a class="cell" href="<?php wra_u( '/news/' ); ?>"><span class="cell__idx">05</span><span class="cell__title">News</span></a>
            <a class="cell" href="<?php wra_u( '/contact/' ); ?>"><span class="cell__idx">06</span><span class="cell__title">Contact</span></a>
          </div>
        </div>
      </div>
    </section>
  </main>
<?php
get_footer();
