<?php
/* GENERATED by _build/wp_build.py from _build/pages/index.html. Edit the static source and re-run; do not edit this file. */
defined( 'ABSPATH' ) || exit;
wra_page( 'home' );
get_header();
?>
<main id="main">

    <!-- ================= HERO ================= -->
    <section class="hero" aria-labelledby="hero-title" data-interval="7000">
      <div class="hero__frame">
        <figure class="hero__slide hero__slide--rib is-active">
          <img src="<?php echo WRA_A; ?>img/photos/rib-mountain-1920.webp" srcset="<?php echo WRA_A; ?>img/photos/rib-mountain-960.webp 960w, <?php echo WRA_A; ?>img/photos/rib-mountain-1920.webp 1920w" sizes="100vw" width="1920" height="1280" fetchpriority="high" alt="Radio tower on Rib Mountain near Wausau, Wisconsin, rising above autumn trees">
        </figure>
        <figure class="hero__slide hero__slide--lacrosse">
          <img data-src="<?php echo WRA_A; ?>img/photos/lacrosse-towers-1920.webp" data-srcset="<?php echo WRA_A; ?>img/photos/lacrosse-towers-960.webp 960w, <?php echo WRA_A; ?>img/photos/lacrosse-towers-1920.webp 1920w" sizes="100vw" width="1920" height="1440" alt="Two guyed radio towers on open marshland in La Crosse, Wisconsin">
        </figure>
        <figure class="hero__slide hero__slide--beam">
          <img data-src="<?php echo WRA_A; ?>img/photos/ham-beam-1600.webp" data-srcset="<?php echo WRA_A; ?>img/photos/ham-beam-800.webp 800w, <?php echo WRA_A; ?>img/photos/ham-beam-1600.webp 1600w" sizes="100vw" width="1600" height="1600" alt="Amateur radio beam antenna on a lattice tower against a blue sky">
        </figure>
      </div>

      <div class="hero__center">
        <h1 class="hero__heading" id="hero-title"><span class="hero__kicker">Wisconsin Repeater Alliance, Inc.</span> <span class="hero__title">Amateur radio repeater coordination</span></h1>
        <p class="hero__lead">The Wisconsin Repeater Alliance provides fair, transparent and engineering-based frequency coordination for repeater owners, radio clubs and amateur operators across Wisconsin.</p>
        <div class="hero__cta">
          <a class="btn" href="<?php wra_u( '/frequency-coordination/' ); ?>">How Coordination Works</a>
          <a class="btn btn--line" href="<?php wra_u( '/membership/' ); ?>">Become a Member</a>
        </div>
      </div>

      <!-- Keyboard and screen-reader users can still stop the background images (WCAG 2.2.2); the button only appears on focus -->
      <button class="hero__pause" type="button">Pause background images</button>
    </section>

    <!-- ================= QUICK ACCESS ================= -->
    <section class="quick" aria-labelledby="quick-title">
      <h2 class="visually-hidden" id="quick-title">Quick access</h2>
      <div class="wrap">
        <div class="quick__grid">
          <a class="qcell" href="<?php wra_u( '/repeater-coordination/' ); ?>">
            <span class="qcell__idx">01</span>
            <span class="qcell__title">Apply for Coordination</span>
            <span class="qcell__text">Apply for a new system, update an existing one, or resolve interference.</span>
            <span class="qcell__foot">Requirements and steps</span>
          </a>
          <a class="qcell qcell--ext" href="https://arcsonline.org/repeaters/" target="_blank" rel="noopener">
            <span class="qcell__idx">02</span>
            <span class="qcell__title">Look Up a Repeater</span>
            <span class="qcell__text">Search coordinated repeaters by callsign, frequency or location in the public directory of the Amateur Radio Coordination System (ARCS).</span>
            <span class="qcell__foot">arcsonline.org<span class="visually-hidden"> (opens in a new tab)</span></span>
          </a>
          <a class="qcell" href="<?php wra_u( '/membership/' ); ?>">
            <span class="qcell__idx">03</span>
            <span class="qcell__title">Join or Renew</span>
            <span class="qcell__text">Support Wisconsin's repeater infrastructure for just $20 a year.</span>
            <span class="qcell__foot">Membership</span>
          </a>
          <a class="qcell qcell--ext" href="https://arcsonline.org/" target="_blank" rel="noopener">
            <span class="qcell__idx">04</span>
            <span class="qcell__title">ARCS Login</span>
            <span class="qcell__text">Sign in to ARCS, the platform WRA uses for coordination.</span>
            <span class="qcell__foot">arcsonline.org<span class="visually-hidden"> (opens in a new tab)</span></span>
          </a>
        </div>
      </div>
    </section>

    <!-- ================= WHO WE ARE ================= -->
    <section class="who" id="who" aria-labelledby="who-title">
      <div class="wrap grid who__grid">
        <figure class="who__media">
          <div class="frame" data-reveal="mask">
            <img class="who__img" src="<?php echo WRA_A; ?>img/photos/member-site-install-1400.webp" srcset="<?php echo WRA_A; ?>img/photos/member-site-install-700.webp 700w, <?php echo WRA_A; ?>img/photos/member-site-install-1400.webp 1400w" sizes="(max-width: 900px) 100vw, 40vw" width="1400" height="1867" loading="lazy" alt="A WRA member climbing a red and white tower to service antennas at a coordinated repeater site">
          </div>
        </figure>
        <div class="who__body" data-reveal style="--d:.1s">
          <h2 class="eyebrow" id="who-title">Who we are</h2>
          <p class="statement">Supporting repeater owners across Wisconsin</p>
          <p class="lead">The Wisconsin Repeater Alliance, Inc. (WRA) is a nonprofit organization dedicated to the responsible coordination and management of amateur radio repeater systems throughout Wisconsin.</p>
          <p class="body-copy">Through sound engineering practices, collaboration and transparency, we help repeater owners, radio clubs and amateur operators make the best possible use of the amateur radio spectrum while minimizing interference and preserving reliable communications.</p>
          <p class="body-copy">Whether you are applying for a new repeater, updating an existing system, or searching for coordinated repeater information, WRA provides the resources and guidance the Wisconsin amateur radio community needs.</p>
          <div class="ruler">
            <div class="ruler__top"><span class="meta">Wisconsin nonprofit corporation</span><a class="alink" href="<?php wra_u( '/about/' ); ?>">About WRA</a></div>
            <div class="ruler__bar" aria-hidden="true"></div>
            <div class="ruler__foot"><span class="meta"><span class="nowrap">501(c)(3)</span> public charity</span></div>
          </div>
        </div>
      </div>
    </section>

    <!-- ================= MAP ================= -->
    <section class="map dark" aria-labelledby="map-heading">
      <div class="wrap grid map__grid">
        <div class="map__text" data-reveal>
          <h2 class="eyebrow" id="map-heading">ARCS public directory</h2>
          <p class="statement">Coordinated repeater records across Wisconsin</p>
          <p class="body-copy">Each mark is a repeater site listed in the public directory of the Amateur Radio Coordination System (ARCS), the platform WRA uses for its coordination work.</p>
          <dl class="stats">
            <div class="stat stat--v"><span class="stat__key" aria-hidden="true"></span><dt><b>2 meters</b>144–148 MHz</dt><dd>165</dd></div>
            <div class="stat stat--u"><span class="stat__key" aria-hidden="true"></span><dt><b>70 centimeters</b>420–450 MHz</dt><dd>183</dd></div>
            <div class="stat stat--x"><span class="stat__key" aria-hidden="true"></span><dt><b>Other bands</b>6 m, 1.25 m, 33 cm and up</dt><dd>40</dd></div>
          </dl>
          <div class="map__actions"><a class="btn btn--white btn--ext" href="https://arcsonline.org/repeaters/" target="_blank" rel="noopener">Search the ARCS directory<span class="visually-hidden">(opens in a new tab)</span></a></div>
          <p class="map__note">Snapshot of the ARCS public directory taken September 30, 2026. Includes records with pending status.</p>
        </div>
        <figure class="map__fig" data-reveal>
          <?php get_template_part( 'template-parts/map' ); ?>
          <div class="map__tip" aria-hidden="true"></div>
        </figure>
      </div>
    </section>

    <!-- ================= JOIN BAR + NEWS ================= -->
    <section class="news" aria-labelledby="news-title">
      <div class="wrap">
        <div class="bar" data-reveal>
          <div>
            <p class="bar__title">Join the effort to protect Wisconsin's amateur radio spectrum</p>
            <p class="bar__text">Members help fund the tools, records and coordination services that keep Wisconsin's repeater network reliable for everyone.</p>
          </div>
          <div class="bar__price"><b>$20</b><span class="meta">A year</span></div>
          <a class="bar__go bar__go--blue" href="<?php wra_u( '/membership/' ); ?>">Become a Member</a>
          <a class="bar__go" href="<?php wra_u( '/resources/#volunteer' ); ?>">Volunteer With Us</a>
        </div>

        <div class="news__head" data-reveal>
          <div>
            <h2 class="eyebrow" id="news-title">News &amp; announcements</h2>
            <p class="statement">Official updates from the Wisconsin Repeater Alliance.</p>
          </div>
          <a class="alink" href="<?php wra_u( '/news/' ); ?>">All news</a>
        </div>

        <?php get_template_part( 'template-parts/news', 'home' ); ?>
      </div>
    </section>
  </main>
<?php
get_footer();
