<?php
/* GENERATED by _build/wp_build.py from _build/pages/terms.html. Edit the static source and re-run; do not edit this file. */
defined( 'ABSPATH' ) || exit;
wra_page( 'terms-of-use' );
get_header();
?>
<main id="main">
    <section class="phead phead--plain" aria-labelledby="page-title">
      <div class="phead__rings" aria-hidden="true"><i></i><i></i><i></i></div>
      <div class="wrap phead__inner">
        <?php wra_crumbs(); ?>
        <h1 class="phead__title" id="page-title">Terms of Use</h1>
        <p class="phead__lead">The terms for using the Wisconsin Repeater Alliance website.</p>
      </div>
    </section>

    <section class="sec sec--first">
      <div class="wrap grid article">
        <!-- EDITABLE: Terms of Use text supplied by WRA (WRA_Website_Terms_of_Use.pdf). -->
        <article class="article__body prose prose--legal">
          <h2 id="purpose">Purpose of the Website</h2>
          <p>The Wisconsin Repeater Alliance (WRA) is a Wisconsin nonprofit organization dedicated to supporting fair, transparent, technically sound amateur radio repeater and auxiliary station frequency coordination within Wisconsin, along with education, spectrum stewardship, technical assistance, records preservation, and related amateur radio activities. This website is provided for informational, educational, administrative, and coordination-related purposes.</p>
          <h2 id="no-fcc-authority">No FCC Authority</h2>
          <p>The Wisconsin Repeater Alliance is not a government agency and does not issue amateur radio licenses or grant operating authority. Frequency coordination recommendations issued by WRA are technical recommendations intended to minimize interference and promote efficient spectrum use. Coordination does not create ownership of a frequency, exclusive use rights, property rights, or any entitlement to spectrum. All amateur radio operators remain subject to applicable FCC rules and regulations.</p>
          <h2 id="accuracy">Accuracy of Information</h2>
          <p>WRA strives to maintain accurate and current information. However, information contained on this website may change without notice. Users are responsible for independently verifying information before relying upon it.</p>
          <h2 id="no-advice">No Technical, Engineering, or Legal Advice</h2>
          <p>Information provided on this website is for general educational and informational purposes only and should not be considered legal advice, engineering certification, regulatory guidance, or professional consulting services.</p>
          <h2 id="conduct">User Conduct</h2>
          <p>Users agree not to use the website for unlawful purposes, attempt unauthorized access, interfere with website operations, submit false information, upload malicious software, collect personal information without authorization, or harass other users or WRA representatives.</p>
          <h2 id="coordination-data">Coordination Data and Public Records</h2>
          <p>Certain coordination information may be published as part of WRA&rsquo;s public technical mission. Submission of coordination requests constitutes consent for WRA to use submitted technical information as necessary to administer coordination functions.</p>
          <h2 id="privacy">Privacy</h2>
          <p>WRA is committed to protecting personal information and maintaining reasonable cybersecurity practices. Personal data will be used only for legitimate organizational and coordination purposes.</p>
          <h2 id="intellectual-property">Intellectual Property</h2>
          <p>Unless otherwise indicated, website content, logos, graphics, forms, publications, software, and original materials are the property of WRA or used under lawful authority. Users may view and download publicly available information for personal and educational use only.</p>
          <h2 id="third-party-links">Third-Party Links</h2>
          <p>WRA is not responsible for the content, policies, or services of third-party websites linked from this website.</p>
          <h2 id="liability">Limitation of Liability</h2>
          <p>To the fullest extent permitted by law, WRA and its officers, directors, volunteers, coordinators, advisors, and representatives shall not be liable for technical errors, coordination disputes, interference issues, data inaccuracies, website outages, data loss, or damages arising from use of this website.</p>
          <h2 id="warranties">Disclaimer of Warranties</h2>
          <p>This website and all information contained within it are provided AS IS and AS AVAILABLE without warranties of any kind.</p>
          <h2 id="changes">Changes to These Terms</h2>
          <p>WRA may modify these Terms of Use at any time. Continued use of the website after changes are posted constitutes acceptance of the revised Terms.</p>
          <h2 id="governing-law">Governing Law</h2>
          <p>These Terms of Use shall be governed by the laws of the State of Wisconsin.</p>
          <h2 id="coordination-disclaimer">Amateur Radio Coordination Disclaimer</h2>
          <p>The Wisconsin Repeater Alliance serves as an amateur radio frequency coordination organization. Frequency coordination recommendations are intended to promote cooperative spectrum use and reduce interference. WRA does not assign frequencies, issue FCC licenses, grant spectrum ownership rights, or provide exclusive use of any amateur radio frequency.</p>
          <h2 id="contact">Contact</h2>
          <p>Questions about these Terms of Use can be sent to:</p>
          <address class="prose__address">Wisconsin Repeater Alliance, Inc.<br>1148 N. Sunnyslope Dr<br>Mount Pleasant, WI 53406<br><a class="inline-link" href="mailto:info@wi-ra.org">info@wi-ra.org</a></address>
        </article>
        <aside class="article__aside article__aside--sticky" aria-label="Terms sections">
          <div class="aside-block">
            <p class="meta" style="margin-bottom:1rem">On this page</p>
            <ol class="legal-toc" role="list"><li><a href="#purpose">Purpose of the Website</a></li><li><a href="#no-fcc-authority">No FCC Authority</a></li><li><a href="#accuracy">Accuracy of Information</a></li><li><a href="#no-advice">No Technical, Engineering, or Legal Advice</a></li><li><a href="#conduct">User Conduct</a></li><li><a href="#coordination-data">Coordination Data and Public Records</a></li><li><a href="#privacy">Privacy</a></li><li><a href="#intellectual-property">Intellectual Property</a></li><li><a href="#third-party-links">Third-Party Links</a></li><li><a href="#liability">Limitation of Liability</a></li><li><a href="#warranties">Disclaimer of Warranties</a></li><li><a href="#changes">Changes to These Terms</a></li><li><a href="#governing-law">Governing Law</a></li><li><a href="#coordination-disclaimer">Amateur Radio Coordination Disclaimer</a></li><li><a href="#contact">Contact</a></li></ol>
          </div>
        </aside>
      </div>
    </section>
  </main>
<?php
get_footer();
