<?php
/* GENERATED by _build/wp_build.py from _build/pages/contact.html. Edit the static source and re-run; do not edit this file. */
defined( 'ABSPATH' ) || exit;
wra_page( 'contact' );
get_header();
?>
<main id="main">
    <section class="phead phead--plain" aria-labelledby="page-title">
      <div class="phead__rings" aria-hidden="true"><i></i><i></i><i></i></div>
      <div class="wrap phead__inner">
        <?php wra_crumbs(); ?>
        <h1 class="phead__title" id="page-title">Contact the Wisconsin Repeater Alliance</h1>
        <p class="phead__lead">Questions about coordination, membership or volunteering? Send us a message and a member of the team will get back to you.</p>
      </div>
    </section>

    <nav class="toc wrap" aria-label="Contact routes">
      <ul class="toc__list" role="list">
        <li><a href="<?php wra_u( '/contact/?topic=coordination#message' ); ?>"><small>01</small>Coordination enquiry</a></li>
        <li><a href="<?php wra_u( '/contact/?topic=interference#message' ); ?>"><small>02</small>Report interference</a></li>
        <li><a href="<?php wra_u( '/contact/?topic=membership#message' ); ?>"><small>03</small>Membership</a></li>
        <li><a href="<?php wra_u( '/contact/?topic=volunteering#message' ); ?>"><small>04</small>Volunteering</a></li>
      </ul>
    </nav>

    <section class="sec sec--first" id="message" aria-labelledby="msg-h">
      <div class="wrap grid split">
        <div class="split__head" data-reveal>
          <h2 class="eyebrow" id="msg-h">Get in touch</h2>
          <p class="statement">Who should contact us</p>
          <p class="body-copy" style="margin-top:1.25rem">Our contact channels are open to repeater owners, amateur radio operators, amateur radio clubs, WRA members and other Wisconsin stakeholders.</p>
          <p class="body-copy">If your inquiry relates to a specific repeater, including your callsign and site location helps us respond more quickly.</p>
          <p class="body-copy">The Wisconsin Repeater Alliance welcomes inquiries from repeater owners, amateur radio operators, clubs, members and other Wisconsin stakeholders. Whether you're asking about a new coordination, an existing system, membership or how to get involved, use the form and we'll respond as soon as we can.</p>
          <dl class="ledger ledger--stack">
            <div><dt>Email</dt><dd><a class="inline-link" href="mailto:info@wi-ra.org">Info@wi-ra.org</a></dd></div>
            <div><dt>Mailing address</dt><dd>1148 N. Sunnyslope Dr, Mount Pleasant, WI 53406</dd></div>
            <div><dt>Platform account help</dt><dd>For help with your Amateur Radio Coordination System (ARCS) account, choose "Coordination inquiry"</dd></div>
          </dl>
        </div>
        <div class="split__body">
          <form class="form" data-form data-endpoint="<?php echo esc_url( rest_url( 'wra/v1/message' ) ); ?>" data-success="Thank you. A member of the team will get back to you." novalidate data-reveal>
            <?php wra_form_fields( 'contact' ); ?>
            <div class="field"><label for="c-name">Name <span class="req" aria-hidden="true">*</span></label><input id="c-name" name="name" type="text" autocomplete="name" required><p class="field__error" aria-live="polite"></p></div>
            <div class="field"><label for="c-call">Callsign</label><input id="c-call" name="callsign" type="text" autocapitalize="characters" spellcheck="false"><p class="field__error" aria-live="polite"></p></div>
            <div class="field field--full"><label for="c-email">Email <span class="req" aria-hidden="true">*</span></label><input id="c-email" name="email" type="email" autocomplete="email" required><p class="field__error" aria-live="polite"></p></div>
            <div class="field field--full">
              <label for="c-subject">Subject <span class="req" aria-hidden="true">*</span></label>
              <select id="c-subject" name="subject" required>
                <option value="">Choose a subject</option>
                <option data-topic="coordination">Coordination inquiry</option>
                <option data-topic="membership">Membership</option>
                <option data-topic="volunteering">Volunteering</option>
                <option data-topic="interference">Interference report</option>
              </select>
              <p class="field__error" aria-live="polite"></p>
            </div>
            <div class="field field--full"><label for="c-msg">Message <span class="req" aria-hidden="true">*</span></label><textarea id="c-msg" name="message" required></textarea><p class="hint">For a specific repeater, include the callsign, output frequency and site location.</p><p class="field__error" aria-live="polite"></p></div>
            <div class="field field--full"><label class="check"><input type="checkbox" name="consent" value="yes" required>I agree to be contacted in response to my inquiry.</label><p class="field__error" aria-live="polite"></p></div>
            <p class="form__status" role="status"></p>
            <div class="form__foot"><p class="form__note">Fields marked * are required.</p><button class="btn" type="submit">Send message</button></div>
          </form>
        </div>
      </div>
    </section>

    <section class="sec sec--paper" aria-labelledby="read-h">
      <div class="wrap">
        <div class="sec-head" data-reveal>
          <h2 class="eyebrow" id="read-h">Prefer to read first?</h2>
          <p class="body-copy" style="margin-bottom:1.25rem">Many common questions are answered on our <a class="inline-link" href="<?php wra_u( '/resources/#faq' ); ?>">FAQ page</a>, and you can learn more about the coordination process on the <a class="inline-link" href="<?php wra_u( '/repeater-coordination/' ); ?>">Repeater Coordination</a> and <a class="inline-link" href="<?php wra_u( '/frequency-coordination/' ); ?>">What Is Frequency Coordination?</a> pages.</p>
          <p class="statement">Many common questions are already answered</p>
        </div>
        <div class="cells" data-reveal>
          <a class="cell" href="<?php wra_u( '/resources/#faq' ); ?>"><span class="cell__idx">01</span><span class="cell__title">FAQ</span><span class="cell__text">Clear answers about coordination, membership and how WRA works.</span></a>
          <a class="cell" href="<?php wra_u( '/repeater-coordination/' ); ?>"><span class="cell__idx">02</span><span class="cell__title">Repeater coordination</span><span class="cell__text">What to supply, how review works and the pre-application checklist.</span></a>
          <a class="cell" href="<?php wra_u( '/frequency-coordination/' ); ?>"><span class="cell__idx">03</span><span class="cell__title">What is frequency coordination?</span><span class="cell__text">How Wisconsin shares a limited spectrum resource fairly.</span></a>
        </div>
      </div>
    </section>
  </main>
<?php
get_footer();
