<?php
/* GENERATED by _build/wp_build.py from _build/pages/membership.html. Edit the static source and re-run; do not edit this file. */
defined( 'ABSPATH' ) || exit;
wra_page( 'membership' );
get_header();
?>
<main id="main">
    <section class="phead" aria-labelledby="page-title">
      <div class="phead__media"><img src="<?php echo WRA_A; ?>img/photos/ham-operator-1280.webp" width="1280" height="993" alt=""></div>
      <div class="phead__rings" aria-hidden="true"><i></i><i></i><i></i></div>
      <div class="wrap phead__inner">
        <?php wra_crumbs(); ?>
        <h1 class="phead__title" id="page-title">Become a member of the Wisconsin Repeater Alliance</h1>
        <p class="phead__lead">For just $20 a year, help protect Wisconsin's repeater spectrum and support the coordination services the community relies on.</p>
        <div class="btn-row">
          <a class="btn" href="https://www.zeffy.com/en-US/ticketing/wra-memberships" zeffy-form-link="https://www.zeffy.com/embed/ticketing/wra-memberships?modal=true">Join now: $20 a year</a>
          <a class="btn btn--line" href="https://www.zeffy.com/en-US/ticketing/wra-memberships" zeffy-form-link="https://www.zeffy.com/embed/ticketing/wra-memberships?modal=true">Renew your membership</a>
        </div>
      </div>
    </section>

    <nav class="toc wrap" aria-label="On this page">
      <ul class="toc__list" role="list">
        <li><a href="#dues-plate"><small>01</small>Annual dues</a></li>
        <li><a href="#funds"><small>02</small>Where dues go</a></li>
        <li><a href="#benefits"><small>03</small>Member benefits</a></li>
        <li><a href="#dues"><small>04</small>Paying your dues</a></li>
        <li><a href="#governance"><small>05</small>Membership and governance</a></li>
      </ul>
    </nav>

    <section class="sec sec--first" id="dues-plate" aria-labelledby="dues-h">
      <div class="wrap">
        <div class="price" data-reveal>
          <div class="price__plate">
            <p class="meta" style="color:var(--mist)">Annual membership dues</p>
            <p class="price__amount" style="margin-top:1.25rem"><sup>$</sup>20</p>
            <p class="price__per">Per year</p>
            <p class="price__note">Dues are assessed annually from the date you join. Your membership remains active for one year and may be renewed each year thereafter.</p>
          </div>
          <div class="price__body">
            <h2 class="eyebrow" id="dues-h">Become a member</h2>
            <p class="statement statement--sm">Open to everyone who supports the Alliance's mission</p>
            <p class="body-copy" style="margin-top:1.25rem">The Wisconsin Repeater Alliance, Inc. is a member-supported nonprofit dedicated to the responsible coordination and stewardship of amateur radio repeater spectrum throughout Wisconsin. Membership is open to everyone who supports the Alliance's mission of promoting reliable communications, sound engineering practices and effective spectrum management.</p>
            <p class="body-copy">By becoming a member, you help ensure the long-term sustainability of repeater coordination services and the technology that supports them.</p>
            <div class="btn-row">
              <a class="btn" href="https://www.zeffy.com/en-US/ticketing/wra-memberships" zeffy-form-link="https://www.zeffy.com/embed/ticketing/wra-memberships?modal=true">Join now</a>
              <a class="btn btn--ghost" href="https://www.zeffy.com/en-US/ticketing/wra-memberships" zeffy-form-link="https://www.zeffy.com/embed/ticketing/wra-memberships?modal=true">Renew</a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="sec sec--paper" id="funds" aria-labelledby="funds-h">
      <div class="wrap grid split">
        <div class="split__head" data-reveal>
          <h2 class="eyebrow" id="funds-h">Where your membership dollars go</h2>
          <p class="statement">Tools, records and coordination services</p>
          <p class="body-copy" style="margin-top:1.25rem">Every membership helps strengthen the technical infrastructure and operational capability needed to provide modern, reliable repeater coordination for Wisconsin.</p>
        </div>
        <div class="split__body">
          <ul class="cells" role="list" data-reveal>
            <li class="cell"><span class="cell__idx">01</span><span class="cell__title">Operation and maintenance of the Amateur Radio Coordination System (ARCS)</span></li>
            <li class="cell"><span class="cell__idx">02</span><span class="cell__title">Website hosting and digital services</span></li>
            <li class="cell"><span class="cell__idx">03</span><span class="cell__title">Online repeater coordination tools</span></li>
            <li class="cell"><span class="cell__idx">04</span><span class="cell__title">Repeater database management</span></li>
            <li class="cell"><span class="cell__idx">05</span><span class="cell__title">Record preservation and backups</span></li>
            <li class="cell"><span class="cell__idx">06</span><span class="cell__title">Public repeater directory services</span></li>
            <li class="cell"><span class="cell__idx">07</span><span class="cell__title">Mapping and engineering resources</span></li>
            <li class="cell"><span class="cell__idx">08</span><span class="cell__title">Administrative and operational expenses</span></li>
            <li class="cell"><span class="cell__idx">09</span><span class="cell__title">Educational and outreach initiatives</span></li>
          </ul>
        </div>
      </div>
    </section>

    <section class="sec" id="benefits" aria-labelledby="benefits-h">
      <div class="wrap">
        <div class="sec-head" data-reveal>
          <h2 class="eyebrow" id="benefits-h">Member benefits</h2>
          <p class="statement">As a member of the Wisconsin Repeater Alliance, you help support</p>
        </div>
        <ul class="icols" role="list" data-reveal>
          <li><span class="icol__idx">1 of 6</span><span class="icol__title">Fair and transparent spectrum coordination</span></li>
          <li><span class="icol__idx">2 of 6</span><span class="icol__title">Preservation of Wisconsin repeater records</span></li>
          <li><span class="icol__idx">3 of 6</span><span class="icol__title">Continued operation and maintenance of the ARCS platform</span></li>
          <li><span class="icol__idx">4 of 6</span><span class="icol__title">Improved access to repeater information</span></li>
          <li><span class="icol__idx">5 of 6</span><span class="icol__title">Modern coordination tools and online services</span></li>
          <li><span class="icol__idx">6 of 6</span><span class="icol__title">Long-term organizational stability and growth</span></li>
        </ul>
        <div class="pull" data-reveal style="margin-top:3.5rem;max-width:48rem"><p>Most importantly, your membership demonstrates your commitment to preserving and strengthening amateur radio communications throughout Wisconsin.</p></div>
      </div>
    </section>

    <section class="sec sec--navy dark" id="dues" aria-labelledby="pay-h">
      <div class="wrap">
        <div class="grid band__head">
          <div data-reveal>
            <h2 class="eyebrow" id="pay-h">How to pay your membership dues</h2>
            <p class="statement">Secure online payment through Zeffy, and 100% of your $20 goes directly to the Wisconsin Repeater Alliance.</p>
          </div>
        </div>
        <div class="icols icols--2" style="margin-top:clamp(3rem,2rem + 3vw,4.5rem)">
          <div data-reveal>
            <span class="icol__idx">1 of 4</span><h3 class="icol__title">Paying your dues</h3>
            <p class="icol__text">The Wisconsin Repeater Alliance, Inc. uses Zeffy as its online membership and payment platform. Annual membership dues are $20 per year, beginning on the date you join and renewing annually thereafter.</p>
          </div>
          <div data-reveal style="--d:.06s">
            <span class="icol__idx">2 of 4</span><h3 class="icol__title">Why we use Zeffy</h3>
            <p class="icol__text">As a nonprofit, the Wisconsin Repeater Alliance works to ensure that membership dollars directly support our mission and operations. Zeffy is a fundraising and payment platform designed specifically for nonprofits. Unlike many payment processors, Zeffy does not charge platform fees, transaction fees or credit card processing fees to nonprofits. This means 100% of your $20 membership payment goes directly to the Wisconsin Repeater Alliance and supports:</p>
            <ul class="ticks ticks--one" role="list" style="margin-top:1rem">
              <li>Operation and maintenance of the Amateur Radio Coordination System (ARCS)</li>
              <li>Website hosting and digital services</li>
              <li>Online coordination and membership tools</li>
              <li>Database management and record preservation</li>
              <li>Organizational operations</li>
              <li>Community outreach and educational initiatives</li>
            </ul>
          </div>
          <div data-reveal>
            <span class="icol__idx">3 of 4</span><h3 class="icol__title">Understanding Zeffy's optional contribution</h3>
            <p class="icol__text">During checkout, Zeffy may suggest an optional contribution to help support the Zeffy platform. This contribution is not part of your Wisconsin Repeater Alliance membership dues and is completely voluntary. If you choose not to contribute to Zeffy, the Wisconsin Repeater Alliance still receives 100% of your membership payment. You are free to accept the suggested contribution, change the amount, reduce it, or remove it entirely. Your membership status and benefits are not affected either way.</p>
          </div>
          <div data-reveal style="--d:.06s">
            <span class="icol__idx">4 of 4</span><h3 class="icol__title">Membership confirmation</h3>
            <p class="icol__text">Once your payment is complete, you will receive a confirmation email from Zeffy documenting your membership transaction. Your membership will remain active for one year from the date of payment.</p>
          </div>
        </div>
        <div class="grid" style="margin-top:3.5rem">
          <div class="col-7" data-reveal>
            <h3 class="sheet__title" style="color:var(--white)">Questions?</h3>
            <p class="body-copy" style="margin-top:0.75rem">If you have questions about membership payments, renewals or your membership status, please <a class="inline-link" href="<?php wra_u( '/contact/?topic=membership' ); ?>">contact the Wisconsin Repeater Alliance</a>. Thank you for supporting the Wisconsin Repeater Alliance and helping us build a stronger future for amateur radio repeater coordination in Wisconsin.</p>
          </div>
          <div class="col-end-4" data-reveal>
            <p class="body-copy" style="margin-bottom:1rem">Ready to join or renew? Pay securely in a couple of minutes. 100% of your dues stay with WRA.</p>
            <a class="btn btn--white" href="https://www.zeffy.com/en-US/ticketing/wra-memberships" zeffy-form-link="https://www.zeffy.com/embed/ticketing/wra-memberships?modal=true">Pay dues securely via Zeffy</a>
          </div>
        </div>
      </div>
    </section>

    <section class="sec" id="governance" aria-labelledby="mg-h">
      <div class="wrap grid split">
        <div class="split__head" data-reveal>
          <h2 class="eyebrow" id="mg-h">Membership and governance</h2>
          <p class="statement">Members keep WRA accountable</p>
        </div>
        <div class="split__body" data-reveal style="--d:.08s">
          <p class="body-copy">The Wisconsin Repeater Alliance is governed by a nine-member Board of Directors elected in accordance with the organization's bylaws. Members provide the foundation the Alliance needs to fulfill its mission and remain accountable to the amateur radio community it serves.</p>
          <p class="body-copy">As the organization grows, members may have opportunities to take part in committees, volunteer programs, organizational meetings and leadership development.</p>
          <a class="alink" href="<?php wra_u( '/about/#governance' ); ?>">How WRA is governed</a>
        </div>
      </div>
    </section>

    <section class="endcap" aria-labelledby="end-h">
      <div class="wrap endcap__inner">
        <div data-reveal>
          <h2 class="statement" id="end-h">Join today for $20 a year</h2>
          <p class="body-copy">Support Wisconsin's repeater infrastructure, preserve valuable spectrum resources and contribute to the future of amateur radio coordination.</p>
        </div>
        <div class="btn-row" data-reveal style="--d:.1s">
          <a class="btn" href="https://www.zeffy.com/en-US/ticketing/wra-memberships" zeffy-form-link="https://www.zeffy.com/embed/ticketing/wra-memberships?modal=true">Join Now</a>
          <a class="btn btn--line" href="<?php wra_u( '/resources/#volunteer' ); ?>">Volunteer Instead</a>
        </div>
      </div>
    </section>
  </main>
<?php
get_footer();
