<?php
/* GENERATED by _build/wp_build.py from _build/pages/news.html. Edit the static source and re-run; do not edit this file. */
defined( 'ABSPATH' ) || exit;
wra_page( 'news' );
get_header();
?>
<main id="main">
    <section class="phead phead--plain" aria-labelledby="page-title">
      <div class="phead__rings" aria-hidden="true"><i></i><i></i><i></i></div>
      <div class="wrap phead__inner">
        <?php wra_crumbs(); ?>
        <h1 class="phead__title" id="page-title">News and announcements</h1>
        <p class="phead__lead">Official updates from the Wisconsin Repeater Alliance.</p>
      </div>
    </section>

    <section class="sec sec--first" aria-labelledby="latest-h">
      <div class="wrap">
        <h2 class="eyebrow" id="latest-h">Latest</h2>
        <?php get_template_part( 'template-parts/news', 'list' ); ?>
      </div>
    </section>
  </main>
<?php
get_footer();
